services:
  # --- BASE DE DATOS ---
  db-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=almacen_aifa
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  # --- BACKEND (.NET) ---
  api-almacen:
    build: 
      context: ./AlmacenAIFA.Server
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db-mysql
    environment:
      - ConnectionStrings__DefaultConnection=Server=db-mysql;Database=almacen_aifa;Uid=root;Pwd=root_password;

  # --- FRONTEND (Vite/React) ---
  front-almacen:
    build:
      context: ./almacenaifa.client
      dockerfile: Dockerfile
    ports:
      - "80:80" # Verás tu web entrando a la IP de la PC (sin puerto)
    depends_on:
      - api-almacen